# Generated by Django 5.0.7 on 2024-07-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=300, unique=True),
        ),
    ]
